nome = input('Digite seu nome: ')
peso = float(input('Informe seu peso : '))
alt = float(input('Informe sua Altura : '))
imc = peso/(alt**2)
print (f'{nome} com {peso:.2f}Kg e {alt:.2f}cm de altura seu IMC é {imc:.2f}')